dist: trusty
language: python
python:
    - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - pip install -r requirements_conda.txt
  - pip install -r requirements.txt
before_script:
  - python setup.py build_ext --inplace
script:
  - python setup.py unittests
