dist: focal
sudo: true
language: python
python:
    - "3.9"
install:
  - pip install -r requirements.txt
  - export PYTHONPATH=src
before_script:
  - python setup.py build_ext --inplace
script:
  - python setup.py unittests
