version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.5
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install 7z, unrar
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: compile and build
          command: |
            export PYTHONPATH=src
            python setup.py build_ext --inplace

      - run:
          name: run tests
          command: |
            export PYTHONPATH=src
            python setup.py unittests

      - run:
          name: wheel
          command: |
            export PYTHONPATH=src
            python setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist
            mkdir -p test-reports/src
            cp -r  src/sparkouille test-reports/src

      - store_artifacts:
          path: test-reports
          destination: test-reports
